### ISSUE TITLE
error: 'LL_ADC_PATH_INTERNAL_VBAT' undeclared

### ISSUE THREAD

**Issue by bartagergely** [WeActTC/WeAct_F411CE#2]
If 

`#define MICROPY_HW_ENABLE_ADC       (1)`

is set, then I got the following error during compiling:

```
In file included from machine_adc.c:29:
adc.h: In function 'adc_deselect_vbat':
adc.h:50:29: error: 'LL_ADC_PATH_INTERNAL_VBAT' undeclared (first use in this function)
   50 |         adc_common->CCR &= ~LL_ADC_PATH_INTERNAL_VBAT;
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~
adc.h:50:29: note: each undeclared identifier is reported only once for each function it appears in 
CC machine_timer.c
make: *** [build-WeAct_F411CE-MicroPython/machine_adc.o] Error 1
make: *** Waiting for unfinished jobs....
```

Any ideas how can I fix it?

**Comment by jej** [comment]
Same error...
:((

**Comment by jej** [comment]
Ok... According to this [page](https://github.com/WeActTC/MiniF4-STM32F4x1), the current board definition works with micropython version V1.12-35

I pulled this version and it works. so maybe the studio will update to v1.13 soon?

**Comment by jej** [comment]
Good news, _jugnu-jethi_ provides a fork working with v1.13 : https://github.com/jugnu-jethi/WeAct_F411CE-MicroPython/tree/myFix_FirstTimeBuild

**Comment by reppad** [comment]
Hi, small update to v1.14!
I have also provided few builds on the repo, if you have a standard WeAct F401 or F411 board and you don't know which firmware to choose, the one with the suffix "25MHzHSE_internalFlash" is probably the right one for your board.
https://github.com/reppad/MicroPython_WeActSTM32F4x1_definitions
Enjoy MicroPython !
